name: upgradelink_api_dart
version: 1.0.2
description: upgradelink_api_dart.
repository: https://github.com/toolsetlink/upgradelink-api-dart
homepage: https://github.com/toolsetlink/upgradelink-api-dart
issue_tracker: https://github.com/toolsetlink/upgradelink-api-dart

environment:
  sdk: ">=2.0.0"

dependencies:
  http: ">=0.13.0"
  intl: ">=0.17.0"
  crypto: ">=2.1.5"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
